1.	Import NumPy in Jupyter notebook.
a.	Generate a 1D NumPy array of 10 random integers between 1 and 100.
b.	Access and print the first and last elements of the array.
c.	Generate a 2D NumPy array of shape (3, 3) with random floating-point numbers.

2.	Use the 2D array generated in Exercise 1 c. Practice slicing arrays to access sub-arrays.
a.	Print the first row of the 2D array.
b.	Print the last column of the 2D array.
c.	Create and print a sub-array consisting of the first two rows and first two columns.

3.	Generate two 1D NumPy arrays of 5 random integers each. 
a.	Add the two arrays and print the result.
b.	Multiply the two arrays (element-wise) and print the result.
c.	Calculate the square of every element in the first array and print it.

4.	Generate two 2D NumPy arrays, A of shape (2, 3) and B of shape (3, 2), with random integers.
a.	Perform matrix multiplication between A and B (using np.dot() or the @ operator) and print the result.
b.	Can A and B perform element-wise multiplication using *, why?



# Import NumPy in Jupyter notebook.

In [1]:
import numpy as np

## a.	Generate a 1D NumPy array of 10 random integers between 1 and 100.

In [3]:
import random

one_d_array = np.array([random.randint(1,100) for i in range(10)])

one_d_array

array([77, 18, 61, 55, 47,  9, 18, 74, 96, 53])

## b.	Access and print the first and last elements of the array.

In [4]:
print(one_d_array[0])

print(one_d_array[-1])

77
53


## c.	Generate a 2D NumPy array of shape (3, 3) with random floating-point numbers.


In [9]:
two_d_array = np.array([[random.random() for i in range(3)] for j in range(3)])

two_d_array

array([[0.81851376, 0.57426448, 0.03939466],
       [0.84620835, 0.80366096, 0.49845867],
       [0.00913619, 0.90703057, 0.41316475]])

# 2.	Use the 2D array generated in Exercise 1 c. Practice slicing arrays to access sub-arrays.

## a.	Print the first row of the 2D array.

In [10]:
print(two_d_array[0])

array([0.81851376, 0.57426448, 0.03939466])

## b.	Print the last column of the 2D array.


In [12]:
print(two_d_array[:,-1])

[0.03939466 0.49845867 0.41316475]


## c.	Create and print a sub-array consisting of the first two rows and first two columns.


In [13]:
print(two_d_array[0:2,0:2])

[[0.81851376 0.57426448]
 [0.84620835 0.80366096]]


# 3.	Generate two 1D NumPy arrays of 5 random integers each. 

In [15]:
arr1 = np.array([random.randint(0, 100) for i in range(5)])
arr2 = np.array([random.randint(0, 100) for i in range(5)])

print(arr1)
print(arr2)

[ 2 97 95 51 27]
[95 46 14 94 93]


## a.	Add the two arrays and print the result.


In [16]:
print(arr1 + arr2)

[ 97 143 109 145 120]


## b.	Multiply the two arrays (element-wise) and print the result.

In [17]:
print(arr1 * arr2)

[ 190 4462 1330 4794 2511]


## c.	Calculate the square of every element in the first array and print it.


In [18]:
print(arr1 ** 2)

[   4 9409 9025 2601  729]


# 4.	Generate two 2D NumPy arrays, A of shape (2, 3) and B of shape (3, 2), with random integers

In [20]:
A = np.array([[random.randint(1,100) for i in range(3)] for i in range(2)])
print(A)
B = np.array([[random.randint(1,100) for i in range(2)] for i in range(3)])
print(B)



[[90 79 82]
 [41 85 66]]
[[12 61]
 [12 81]
 [18 75]]


## a.	Perform matrix multiplication between A and B (using np.dot() or the @ operator) and print the result.


In [22]:
print(A @ B)

[[ 3504 18039]
 [ 2700 14336]]


## b.	Can A and B perform element-wise multiplication using *, why?

They can not. This is because they have different shapes (As shown by the ValueError in the cell below).


In [24]:
print(A * B)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 